name: Build and Package (NSIS)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (root)
        run: npm install

      - name: Install dependencies (http)
        run: |
          cd http
          npm install

      - name: Install dependencies (ui-helper)
        run: |
          cd ui-helper
          npm install

      - name: Create build config
        run: |
          if not exist build\buildMain.config.js (
            copy build\buildMain.config.js.dist build\buildMain.config.js
          )

      - name: Install NSIS
        run: choco install nsis -y

      - name: Build Project
        run: npm run build

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: showKeyBoard-installer
          path: release\
